### ISSUE TITLE
When there is nothing left to validate, show 0

### ISSUE THREAD

**Issue by frodrigo** [teritorio/clearance-frontend#129]
When there is nothing left to validate, show 0. Missing value look ugly and prone to question.

**Comment by wazolab** [comment]
Duplicate of #114 no ?

**Comment by frodrigo** [comment]
No, this one about the missing value here

![image](https://github.com/teritorio/clearance-frontend/assets/1785486/0c017348-3976-4706-9764-15cbd8569ba3)
