### ISSUE TITLE
On change Logs, minimap may be missing

### ISSUE THREAD

**Issue by frodrigo** [teritorio/clearance-frontend#154]
Especially on deleted object, mini map may be broken.

**Comment by wazolab** [comment]
It's because of `null` value from API
We are getting `log.change.geom`:
![image](https://github.com/teritorio/clearance-frontend/assets/38253764/1b16530d-2c5a-41d8-af6a-90f882247248)

**Comment by frodrigo** [comment]
In case of delete object. with have the old version geom we should display it. As the object is deleted, there is no new version (for the ways and relations).

So yes. Just ignore missing geom for the map.
