### ISSUE TITLE
Missing call to API /me

### ISSUE THREAD

**Issue by frodrigo** [teritorio/clearance-frontend#86]
The front should call `/api/0.1/users/me` to get connected user info or know there is no user (404).

**Comment by wazolab** [comment]
I'm not sure to understand the request ?
As of today we are calling this API endpoint only if we have the cookie in the browser. This way we avoid to trigger a 404 "for nothing".
Thus, if we have a cookie and the API call returns an error, we have a message notification poping on user screen.
Isn't it enought ?

**Comment by frodrigo** [comment]
On dev server, the cookie is there, but it does not work as expected.

**Comment by wazolab** [comment]
In dev, the redirection from the API looks broken to me  ...
Ex: https://clearance-dev.teritorio.xyz/users/auth/osm_oauth2/callback?code=fMzmL7rZHcKzGYHnm75_A2WZibwSPyMZGWYMJmAtIXo&state=222e5c702c73abb2eb65b13b3a3abfa8383c253c9559c9c8

It looks like Dev API isn't handling callback function right ...

**Comment by wazolab** [comment]
Instead of shouting error when no-cookie, invite user to connect
